apiVersion: v1
kind: Service
metadata:
  name: {{ include "poke-manifests.fullname" . }}
  labels:
    {{- include "poke-manifests.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "poke-manifests.selectorLabels" . | nindent 4 }}